apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: $INFLUXDB_ORG
      defaultBucket: $INFLUXDB_BUCKET
      tlsSkipVerify: true
    secureJsonData:
      token: $INFLUXDB_ADMIN_TOKEN

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogsV2:
        datasourceUid: opensearch
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        filterByTraceID: true

  - name: OpenSearch Logs
    uid: opensearch
    type: elasticsearch
    access: proxy
    url: http://opensearch:9200
    database: "logs-*"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "7.10.0"
      logMessageField: message
      logLevelField: level
