server {
    listen 80;
    default_type application/json;

    location / {
        root /usr/share/nginx/html;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "no-store";
    }
}
